data_processing:
  context_col : context
  question_col: question
  answer_col: text
  answer_start_col: answer_start

  train_data_size: 0.8
  val_data_size: 0.2

model_params:
  model_type: bert
  model_name: bert-base-cased
  epochs: 2
  train_batch_size : 8
  val_batch_size: 4
  