data_processing:
  answer_col: text
  answer_start_col: None
  context_col: context
  question_col: question
  train_data_size: 0.8
  val_data_size: 0.1
model_params:
  epochs: 10
  model_name: distilbert-base-cased
  model_type: distilbert
  train_batch_size: 4
  val_batch_size: 4
