artifacts_root: artifacts


data_ingestion:
  raw_data_dir: artifacts/raw_data
  web_data_dir: web_files

data_processing:
  raw_data_dir: artifacts/raw_data
  processed_data_dir: artifacts/processed_data
  split_data_dir: artifacts/split_data