artifacts_root: artifacts

data_ingestion:
  raw_data_dir: artifacts/raw_data
  web_data_dir: web_files

data_processing:
  raw_data_dir: artifacts/raw_data
  processed_data_dir: artifacts/processed_data
  split_data_dir: artifacts/split_data

train_model:
  train_data_path: artifacts/split_data/train_data.json
  val_data_path : artifacts/split_data/val_data.json
  save_model_dir: artifacts/models
  
model_eval:
  save_model_dir: artivacts/models

